# Generated by Django 4.2.9 on 2024-08-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxmart', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
