# Generated by Django 4.2.9 on 2024-01-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxmart', '0005_category_product_delete_car'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='tbl_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='tbl_product',
        ),
    ]
