# Generated by Django 4.2.9 on 2024-01-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luxmart', '0007_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxmart.cartitem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxmart.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='luxmart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxmart.product')),
            ],
            options={
                'db_table': 'tbl_ordetail',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(related_name='orders', through='luxmart.OrderDetail', to='luxmart.cartitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(related_name='orders', through='luxmart.OrderDetail', to='luxmart.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='luxmart.OrderDetail', to='luxmart.product'),
        ),
    ]
